services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules

    command: sleep infinity

    networks:
      - internal_network
      - external_network

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: unless-stopped
    image: postgres:15-alpine
    networks:
      - internal_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: misskey
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

  elasticsearch:
    image: elasticsearch:8.18.2
    container_name: elasticsearch_single_node
    environment:
      - discovery.type=single-node

      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # 開発用にセキュリティ機能を無効化
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - internal_network

  kibana:
    image: elastic/kibana:8.18.2
    ports:
      - 5601:5601
    networks:
      - internal_network
      - external_network

volumes:
  postgres-data:
  redis-data:
  node_modules:
  esdata:
    driver: local

networks:
  internal_network:
    internal: true
  external_network:
